In [46]:
import pandas as pd

# Load the CSV files
matches_df = pd.read_csv('data/epic7_matches.csv')

matches_df.head()

,my_team_picks,enemy_team_picks,my_bans,enemy_bans,first_pick_team,winner
0,"[{""hero_code"": ""c1153"", ""pick_order"": 2}, {""he...","[{""hero_code"": ""c5110"", ""pick_order"": 1}, {""he...","[""c2066"", ""c2011""]","[""c1133"", ""c2042""]",enemy_team,enemy_team
1,"[{""hero_code"": ""c2112"", ""pick_order"": 2}, {""he...","[{""hero_code"": ""c2106"", ""pick_order"": 1}, {""he...","[""c2066"", ""c2011""]","[""c1153"", ""c1133""]",enemy_team,my_team
2,"[{""hero_code"": ""c1153"", ""pick_order"": 2}, {""he...","[{""hero_code"": ""c2066"", ""pick_order"": 1}, {""he...","[""c4158"", ""c2011""]","[""c2090"", ""c2042""]",enemy_team,my_team
3,"[{""hero_code"": ""c2112"", ""pick_order"": 1}, {""he...","[{""hero_code"": ""c2090"", ""pick_order"": 2}, {""he...","[""c2011"", ""c4158""]","[""c1133"", ""c1153""]",my_team,my_team
4,"[{""hero_code"": ""c5110"", ""pick_order"": 1}, {""he...","[{""hero_code"": ""c2090"", ""pick_order"": 2}, {""he...","[""c2011"", ""c4158""]","[""c2112"", ""c1151""]",my_team,my_team

In [47]:
# Iterate over each match and apply the rules
lst = []
for index, row in matches_df.iterrows():
    winner = row['winner']  # Adjust this if your column name is different
    
    # Map winner to my_team and loser to enemy_team
    first_pick_mapping = {'my_team':'winning_team', 'enemy_team':'losing_team'} if winner == 'my_team' else {'my_team':'losing_team', 'enemy_team':'winning_team'}
    mapping = {'winning_team':'my', 'losing_team':'enemy'} if winner == 'my_team' else {'winning_team':'enemy', 'losing_team':'my'}

    new_row = {
        'winning_team_picks': row[mapping['winning_team'] + '_team_picks'],
        'losing_team_picks': row[mapping['losing_team'] + '_team_picks'],
        'winning_team_bans': row[mapping['winning_team'] + '_bans'],
        'losing_team_bans': row[mapping['losing_team'] + '_bans'],
        'first_pick_team': first_pick_mapping[row['first_pick_team']] 
    }

    # Append the new row
    lst.append(new_row)

    
# Initialize a new DataFrame to store the rearranged data
new_matches_df = pd.DataFrame(lst, columns=[
    'winning_team_picks',
    'losing_team_picks',
    'winning_team_bans',
    'losing_team_bans',
    'first_pick_team'
])

# Save the new DataFrame to a CSV file
new_matches_df.to_csv('data/rearranged_epic7_matches.csv', index=False)
print('Rearranged data has been saved to data/rearranged_epic7_matches.csv')

new_matches_df.head()

Rearranged data has been saved to data/rearranged_epic7_matches.csv

,winning_team_picks,losing_team_picks,winning_team_bans,losing_team_bans,first_pick_team
0,"[{""hero_code"": ""c5110"", ""pick_order"": 1}, {""he...","[{""hero_code"": ""c1153"", ""pick_order"": 2}, {""he...","[""c1133"", ""c2042""]","[""c2066"", ""c2011""]",winning_team
1,"[{""hero_code"": ""c2112"", ""pick_order"": 2}, {""he...","[{""hero_code"": ""c2106"", ""pick_order"": 1}, {""he...","[""c2066"", ""c2011""]","[""c1153"", ""c1133""]",losing_team
2,"[{""hero_code"": ""c1153"", ""pick_order"": 2}, {""he...","[{""hero_code"": ""c2066"", ""pick_order"": 1}, {""he...","[""c4158"", ""c2011""]","[""c2090"", ""c2042""]",losing_team
3,"[{""hero_code"": ""c2112"", ""pick_order"": 1}, {""he...","[{""hero_code"": ""c2090"", ""pick_order"": 2}, {""he...","[""c2011"", ""c4158""]","[""c1133"", ""c1153""]",winning_team
4,"[{""hero_code"": ""c5110"", ""pick_order"": 1}, {""he...","[{""hero_code"": ""c2090"", ""pick_order"": 2}, {""he...","[""c2011"", ""c4158""]","[""c2112"", ""c1151""]",winning_team